name: narrately
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.4.3
  file_picker: ^13.1.0
  epub_pro: ^5.6.0
  image: ^4.10.1
  uuid: ^4.6.0
  flutter_tts: ^4.2.5
  archive: ^4.3.0
  sqflite: ^2.4.4
  path_provider: ^2.1.6
  path: ^1.9.1
  audio_service: ^0.18.19
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_pdf: ^33.2.13
  permission_handler: ^13.0.2
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon.png"
  adaptive_icon_foreground: "assets/transparent.png"
